import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Providers } from "./providers";
import { AiBehaviorMonitor } from "page-sense-library";
import { Toaster } from 'sonner';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="fixed top-0 left-0 w-full bg-black text-white text-xs px-4 py-1 flex gap-4 z-50 justify-center font-mono shadow-md">
          <span className="text-gray-400">TEST SITES:</span>
          <a href="/" className="hover:text-blue-400 transition">Ecommerce</a>
          <a href="/blog" className="hover:text-blue-400 transition">Blog</a>
          <a href="/dashboard" className="hover:text-blue-400 transition">SaaS Dashboard</a>
          <a href="/portfolio" className="hover:text-blue-400 transition">Portfolio</a>
        </div>
        <Providers>
          <div className="mt-6"> {/* push content down to avoid overlap with fixed switcher */}
            {children}
          </div>
          <AiBehaviorMonitor />
          <Toaster position="top-center" />
        </Providers>
      </body>
    </html>
  );
}
